dubbo:
  application:
    name: dubbo-sp-demo-consumer
    qos-enable: false
    #FORCE_APPLICATION 应用级订阅
    # APPLICATION_FIRST (默认),既有接口应用订阅应用级订阅
#    FORCE_INTERFACE 接口级订阅
#    service-discovery: # 新增此配置块
#      migration: FORCE_INTERFACE
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://127.0.0.1:2181
#    use-application-first: false
#    parameters:
#      registry-type: service
  consumer:
    check: false

server:
  port: 8081