dubbo:
  application:
    name: dubbo-sp-demo-provider
    qos-enable: false
    #默认local
    metadata-type: remote
    register-mode: all
#    register-mode: instance
#    register-mode: interface
  registry:
    address: zookeeper://127.0.0.1:2181
    scope: remote
#    use-as-config-center: false
#    use-as-metadata-center: false
#    parameters:
#      registry-type: service
  protocols:
    p1:
      name: dubbo
      port: 20881
#    p2:
#      name: rest
#      port: 8085
#    p3:
#      name: tri
#      port: 20883

server:
  port: 8082
