#spring:
#  application:
#    name: dubbo-springboot-demo-provider
#
#dubbo:
#  application:
#    name: ${spring.application.name}
#  protocol:
#    name: tri
#    port: -1
#  registry:
#    id: zk-registry
#    address: zookeeper://127.0.0.1:2181
#  config-center:
#    address: zookeeper://127.0.0.1:2181
#  metadata-report:
#    address: zookeeper://127.0.0.1:2181
#  metrics:
#    protocol: prometheus
#    enable-jvm: true
#    enable-registry: true
#    aggregation:
#      enabled: true
#    prometheus:
#      exporter:
#        enabled: true
#    enable-metadata: true
